server:
  servlet:
    context-path: /rabbitmq-message-publisher
management:
  server:
    port: 8081
    servlet:
      context-path: /rabbitmq-message-publisher
  endpoints:
    web:
      base-path: /


spring:
  rabbitmq:
    host:
    port:
    userName:
    password:
    exchange:
    queue:
    routing-key:

validCustomerTypes:  Permanent,Contract,Internal